
--- Trueshot lodge sentinel detection announcement text
DELETE FROM creature_text WHERE CreatureID IN (100709, 100491, 103444);
INSERT INTO creature_text (CreatureID, GroupID, ID, Text, Type, Language, Probability, Emote, Duration, Sound, BroadcastTextId, TextRange, comment) VALUES 
(100709, 0, 0, 'This sacred peak is for hunters alone. Turn back, or the eagle spirit will carry you away!', 42, 0, 100, 0, 0, 0, 0, 0, ''),
(100491, 0, 0, 'This sacred peak is for hunters alone. Turn back, or the eagle spirit will carry you away!', 42, 0, 100, 0, 0, 0, 0, 0, ''),
(103444, 0, 0, 'This sacred peak is for hunters alone. Turn back, or the eagle spirit will carry you away!', 42, 0, 100, 0, 0, 0, 0, 0, '');

INSERT INTO creature_text_locale (CreatureID, GroupID, ID, Locale, Text) VALUES 
(100709, 0, 0, 'ruRU', 'На эту священную вершину допускаются только охотники, Поворачивайте назад, или дух орла унесет вас отсюда!'),
(100491, 0, 0, 'ruRU', 'На эту священную вершину допускаются только охотники, Поворачивайте назад, или дух орла унесет вас отсюда!'), 
(103444, 0, 0, 'ruRU', 'На эту священную вершину допускаются только охотники, Поворачивайте назад, или дух орла унесет вас отсюда!');

--- fix npc 95772 damage spell
UPDATE `creature_template` SET `entry`='95772', `difficulty_entry_1`='0', `difficulty_entry_2`='0', `difficulty_entry_3`='0', `KillCredit1`='0', `KillCredit2`='0', `modelid1`='64385', `modelid2`='64541', `modelid3`='0', `modelid4`='0', `name`='Frenzied Nightclaw', `femaleName`='', `subname`='', `TitleAlt`=NULL, `IconName`='', `gossip_menu_id`='0', `minlevel`='98', `maxlevel`='110', `HealthScalingExpansion`='6', `RequiredExpansion`='0', `VignetteID`='0', `faction`='16', `npcflag`='0', `speed_walk`='1', `speed_run`='1', `scale`='1', `rank`='1', `dmgschool`='0', `BaseAttackTime`='2000', `RangeAttackTime`='2000', `BaseVariance`='1', `RangeVariance`='1', `unit_class`='4', `unit_flags`='32832', `unit_flags2`='2099200', `unit_flags3`='0', `dynamicflags`='0', `family`='2', `trainer_type`='0', `trainer_class`='0', `trainer_race`='0', `type`='1', `type_flags`='2097224', `type_flags2`='0', `lootid`='95772', `pickpocketloot`='0', `skinloot`='95772', `resistance1`='0', `resistance2`='0', `resistance3`='0', `resistance4`='0', `resistance5`='0', `resistance6`='0', `spell1`='0', `spell2`='0', `spell3`='0', `spell4`='0', `spell5`='0', `spell6`='0', `spell7`='0', `spell8`='0', `VehicleId`='0', `mingold`='0', `maxgold`='0', `AIName`='SmartAI', `MovementType`='0', `InhabitType`='3', `HoverHeight`='1', `HealthModifier`='4', `HealthModifierExtra`='1', `ManaModifier`='1', `ManaModifierExtra`='1', `ArmorModifier`='1', `DamageModifier`='0.8888', `ExperienceModifier`='1', `RacialLeader`='0', `movementId`='0', `RegenHealth`='1', `mechanic_immune_mask`='0', `flags_extra`='0', `ScriptName`='', `VerifiedBuild`='25549' WHERE (`entry`='95772');
UPDATE `smart_scripts` SET `entryorguid`='95772', `source_type`='0', `id`='0', `link`='0', `event_type`='0', `event_phase_mask`='0', `event_chance`='100', `event_flags`='0', `event_param1`='5000', `event_param2`='8000', `event_param3`='12000', `event_param4`='15000', `event_param_string`='', `action_type`='11', `action_param1`='200620', `action_param2`='0', `action_param3`='0', `action_param4`='0', `action_param5`='0', `action_param6`='0', `target_type`='2', `target_param1`='0', `target_param2`='0', `target_param3`='0', `target_x`='0', `target_y`='0', `target_z`='0', `target_o`='0', `comment`='Cast Frantic Rip' WHERE (`entryorguid`='95772') AND (`source_type`='0') AND (`id`='0') AND (`link`='0');