INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param_string`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('108853', '0', '2', '0', '1', '0', '100', '0', '0', '0', '0', '0', '', '41', '17994', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'Despawn Great Eagle');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param_string`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('108853', '0', '1', '0', '1', '0', '100', '0', '18000', '18000', '18000', '18000', '', '11', '216216', '0', '0', '0', '0', '0', '21', '2', '0', '0', '0', '0', '0', '0', 'Telepot oplot hunt');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param_string`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('108868', '0', '0', '0', '62', '0', '100', '0', '999912', '0', '0', '0', '', '85', '216213', '0', '0', '0', '0', '0', '7', '0', '0', '0', '0', '0', '0', '0', 'Caset Great Eagle');
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `event_param_string`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES ('108853', '0', '0', '0', '11', '0', '100', '0', '0', '0', '0', '0', '', '53', '1', '9999991', '0', '0', '6', '0', '1', '0', '0', '0', '0', '0', '0', '0', 'Waypoint Great Eagle');

INSERT INTO `waypoints` (`entry`, `pointid`, `position_x`, `position_y`, `position_z`, `point_comment`) VALUES ('9999991', '1', '-822.739', '4247.71', '758.094', 'Waypoint Great Eagle');
INSERT INTO `waypoints` (`entry`, `pointid`, `position_x`, `position_y`, `position_z`, `point_comment`) VALUES ('9999991', '2', '-887.436', '4125.42', '747.539', 'Waypoint Great Eagle');


UPDATE creature_template SET  VehicleId = '5416', AIName = 'SmartAI', InhabitType = '4' WHERE entry =108853;
UPDATE `creature_template` SET `entry`='108868', `difficulty_entry_1`='0', `difficulty_entry_2`='0', `difficulty_entry_3`='0', `KillCredit1`='0', `KillCredit2`='0', `modelid1`='67943', `modelid2`='0', `modelid3`='0', `modelid4`='0', `name`='Talua', `femaleName`='', `subname`='Eagle Keeper', `TitleAlt`=NULL, `IconName`='', `gossip_menu_id`='999912', `minlevel`='1', `maxlevel`='1', `HealthScalingExpansion`='6', `RequiredExpansion`='0', `VignetteID`='0', `faction`='35', `npcflag`='1', `speed_walk`='1', `speed_run`='1.14286', `scale`='1', `rank`='0', `dmgschool`='0', `BaseAttackTime`='0', `RangeAttackTime`='0', `BaseVariance`='1', `RangeVariance`='1', `unit_class`='1', `unit_flags`='0', `unit_flags2`='0', `unit_flags3`='0', `dynamicflags`='0', `family`='0', `trainer_type`='0', `trainer_class`='0', `trainer_race`='0', `type`='7', `type_flags`='0', `type_flags2`='0', `lootid`='0', `pickpocketloot`='0', `skinloot`='0', `resistance1`='0', `resistance2`='0', `resistance3`='0', `resistance4`='0', `resistance5`='0', `resistance6`='0', `spell1`='0', `spell2`='0', `spell3`='0', `spell4`='0', `spell5`='0', `spell6`='0', `spell7`='0', `spell8`='0', `VehicleId`='0', `mingold`='0', `maxgold`='0', `AIName`='SmartAI', `MovementType`='0', `InhabitType`='3', `HoverHeight`='1', `HealthModifier`='25', `HealthModifierExtra`='1', `ManaModifier`='1', `ManaModifierExtra`='1', `ArmorModifier`='1', `DamageModifier`='1', `ExperienceModifier`='1', `RacialLeader`='0', `movementId`='0', `RegenHealth`='1', `mechanic_immune_mask`='0', `flags_extra`='0', `ScriptName`='', `VerifiedBuild`='25549' WHERE (`entry`='108868');


INSERT INTO `gossip_menu_option` (`MenuId`, `OptionIndex`, `OptionIcon`, `OptionText`, `OptionBroadcastTextId`, `OptionType`, `OptionNpcFlag`, `VerifiedBuild`) VALUES ('999912', '0', '0', 'I\'\'d like an eagle to Trueshot Lodge.', '0', '1', '1', '0');

INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES ('15', '999912', '0', '0', '0', '15', '0', '4', '0', '0', '0', '0', '0', '', 'Only hunter teleport oplot');

INSERT INTO `gossip_menu_option_locale` (`MenuId`, `OptionIndex`, `Locale`, `OptionText`, `BoxText`) VALUES ('999912', '0', 'ruRU', 'Хочу долететь на орле до Приюта стрелка.', NULL);